name: Build and push Docker image
on:
  push:
    branches:
      - develop
      - docker
    paths:
      - ".github/workflows/docker.yml"
      - ".dockerignore"
      - "Copy/**"

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set variables
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "::set-output name=short_sha::$calculatedSha"
          echo "::set-output name=username::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Copy/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.username }}:${{ steps.vars.outputs.short_sha }}
            ghcr.io/${{ steps.vars.outputs.username }}:latest
